use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result};
use log::info;

use crate::{config::AuditType, prepare_code::git_clone::RepoPaths};

const THREE_SHOT_DIR: &str = "validation-three-shot";
const PROMPT_VERSION: &str = "v2";
const RUN_ID: &str = "run-001";
const V12_CHECKLIST_ENTRY: &str = "{{THREE_SHOT_ROOT}}/v12-checklist.md";
const BOUNTY_CRITERIA_ENTRY: &str = "{{THREE_SHOT_ROOT}}/code4rena-bounty-criteria.md";

pub fn write_protocol_config(repo: &RepoPaths, audit_report_path: &Path) -> Result<PathBuf> {
    let benchmark = config_slug(&repo.repo_name);
    let output_path = PathBuf::from(THREE_SHOT_DIR).join(format!("{benchmark}-config.yaml"));
    let audit_report_path = absolute_path(audit_report_path)?;
    let audit_root = audit_root_from_report(&audit_report_path);
    let source_root = source_root(repo);
    let context_docs = context_docs(repo, &source_root)?;
    let rendered = render_config(
        &benchmark,
        &source_root,
        &audit_root,
        &audit_report_path,
        &context_docs,
        &repo.audit_type,
    );

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create {}", parent.display()))?;
    }
    fs::write(&output_path, rendered)
        .with_context(|| format!("Failed to write {}", output_path.display()))?;
    info!(
        "Wrote three-shot validation config: path={}, benchmark={}, source_root={}, audit_root={}, audit_report={}",
        output_path.display(),
        benchmark,
        source_root.display(),
        audit_root.display(),
        audit_report_path.display()
    );

    Ok(output_path)
}

fn render_config(
    benchmark: &str,
    source_root: &Path,
    audit_root: &Path,
    audit_report_path: &Path,
    context_docs: &[String],
    audit_type: &AuditType,
) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by ai-agent-audit after report export.\n");
    out.push_str(
        "# Edit run_id or prompt_version before launching a new validation run if needed.\n\n",
    );
    out.push_str(&format!("benchmark: {}\n", yaml_scalar(benchmark)));
    out.push_str(&format!(
        "validation_profile: {}\n",
        yaml_scalar(validation_profile(audit_type))
    ));
    out.push_str(&format!("prompt_version: {PROMPT_VERSION}\n"));
    out.push_str(&format!("run_id: {RUN_ID}\n\n"));
    out.push_str("paths:\n");
    out.push_str(&format!(
        "  source_root: {}\n",
        yaml_scalar(&source_root.to_string_lossy())
    ));
    out.push_str(&format!(
        "  audit_root: {}\n",
        yaml_scalar(&audit_root.to_string_lossy())
    ));
    out.push_str(&format!(
        "  audit_report: {}\n\n",
        yaml_scalar(&audit_report_path.to_string_lossy())
    ));
    out.push_str("context_docs:\n");
    for doc in context_docs {
        out.push_str(&format!("  - {}\n", yaml_scalar(doc)));
    }
    out
}

fn validation_profile(audit_type: &AuditType) -> &'static str {
    match audit_type {
        AuditType::Code4rena => "code4rena",
        AuditType::Code4renaBounty => "code4rena-bounty",
        AuditType::ImmunefiBugBounty => "immunefi-bounty",
        _ => "default",
    }
}

fn context_docs(repo: &RepoPaths, source_root: &Path) -> Result<Vec<String>> {
    let project_root = std::env::current_dir()?;
    let mut docs = Vec::new();

    for doc in &repo.docs {
        push_unique_doc(&mut docs, context_doc_entry(doc, &project_root));
    }

    if let Some(scope) = &repo.audit_scope {
        push_unique_doc(&mut docs, context_doc_entry(scope, &project_root));
    }

    if let Some(scoped_files) = &repo.scoped_files {
        push_unique_doc(&mut docs, context_doc_entry(scoped_files, &project_root));
    }

    let readme = source_root.join("README.md");
    if readme.exists() {
        push_unique_doc(&mut docs, "{{SOURCE_ROOT}}/README.md".to_string());
    }

    match repo.audit_type {
        AuditType::Code4rena => push_unique_doc(&mut docs, V12_CHECKLIST_ENTRY.to_string()),
        AuditType::Code4renaBounty => push_unique_doc(&mut docs, BOUNTY_CRITERIA_ENTRY.to_string()),
        AuditType::ImmunefiBugBounty => {}
        _ => {}
    }
    Ok(docs)
}

fn context_doc_entry(path: &Path, project_root: &Path) -> String {
    if let Ok(relative) = path.strip_prefix(project_root) {
        relative.to_string_lossy().to_string()
    } else {
        path.to_string_lossy().to_string()
    }
}

fn push_unique_doc(docs: &mut Vec<String>, value: String) {
    if value.is_empty() {
        return;
    }
    if !docs.iter().any(|doc| doc == &value) {
        docs.push(value);
    }
}

fn absolute_path(path: &Path) -> Result<PathBuf> {
    if path.is_absolute() {
        Ok(path.to_path_buf())
    } else {
        Ok(std::env::current_dir()?.join(path))
    }
}

fn audit_root_from_report(audit_report_path: &Path) -> PathBuf {
    audit_report_path
        .parent()
        .and_then(Path::parent)
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."))
}

fn source_root(repo: &RepoPaths) -> PathBuf {
    let candidate = repo.get_protocol_root();
    if candidate.exists() {
        return candidate;
    }

    common_source_root(&repo.source_code_folders).unwrap_or_else(|| repo.root.clone())
}

fn common_source_root(source_code_folders: &[PathBuf]) -> Option<PathBuf> {
    if source_code_folders.is_empty() {
        return None;
    }

    let mut components = source_code_folders[0]
        .parent()
        .unwrap_or(&source_code_folders[0])
        .components()
        .map(|component| component.as_os_str().to_os_string())
        .collect::<Vec<_>>();

    for folder in &source_code_folders[1..] {
        let other = folder
            .parent()
            .unwrap_or(folder)
            .components()
            .map(|component| component.as_os_str().to_os_string())
            .collect::<Vec<_>>();
        let common_len = components
            .iter()
            .zip(other.iter())
            .take_while(|(left, right)| left == right)
            .count();
        components.truncate(common_len);
    }

    if components.is_empty() {
        return None;
    }

    let mut path = PathBuf::new();
    for component in components {
        path.push(component);
    }
    Some(path)
}

fn config_slug(value: &str) -> String {
    let slug = value
        .trim_end_matches(".git")
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' {
                ch
            } else {
                '-'
            }
        })
        .collect::<String>()
        .trim_matches('-')
        .to_string();
    if slug.is_empty() {
        "protocol".to_string()
    } else {
        slug
    }
}

fn yaml_scalar(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{config::AuditType, prepare_code::git_clone::RepoPaths};

    fn repo_paths(root: PathBuf, docs: Vec<PathBuf>, audit_scope: Option<PathBuf>) -> RepoPaths {
        RepoPaths {
            github_url: "https://github.com/example/protocol/blob/abc123".to_string(),
            project_id: "2026-01-olas-abc123".to_string(),
            root: root.clone(),
            sol_files: Vec::new(),
            test_files: Vec::new(),
            script_files: Vec::new(),
            config_files: Vec::new(),
            lib_config_files: Vec::new(),
            source_code_folders: vec![root.join("2026-01-olas/contracts")],
            docs,
            repo_name: "2026-01-olas".to_string(),
            audit_scope,
            excluded_folders: None,
            scoped_files: None,
            monorepo_folders: None,
            commit_hash: "abc123".to_string(),
            audit_type: AuditType::Code4rena,
        }
    }

    #[test]
    fn generated_config_contains_required_paths_and_v12_checklist() {
        let temp = tempfile::tempdir().unwrap();
        let project = temp.path();
        let source_root = project.join("audit-workspace/2026-01-olas");
        fs::create_dir_all(&source_root).unwrap();
        fs::write(source_root.join("README.md"), "# Olas").unwrap();
        let docs = project.join("audit-docs/2026-01-olas-docs.md");
        let scope = project.join("audit-docs/2026-01-olas-scope.md");
        fs::create_dir_all(docs.parent().unwrap()).unwrap();
        fs::write(&docs, "# Docs").unwrap();
        fs::write(&scope, "# Scope").unwrap();

        let repo = repo_paths(project.join("audit-workspace"), vec![docs], Some(scope));
        let report = project.join("2026-01-olas/report/audit-report.md");
        let rendered = render_config(
            "2026-01-olas",
            &source_root,
            &project.join("2026-01-olas"),
            &report,
            &context_docs(&repo, &source_root).unwrap(),
            &repo.audit_type,
        );

        assert!(rendered.contains("benchmark: \"2026-01-olas\""));
        assert!(rendered.contains("validation_profile: \"code4rena\""));
        assert!(rendered.contains("source_root: "));
        assert!(rendered.contains("audit_root: "));
        assert!(rendered.contains("audit_report: "));
        assert!(rendered.contains("audit-docs/2026-01-olas-docs.md"));
        assert!(rendered.contains("audit-docs/2026-01-olas-scope.md"));
        assert!(rendered.contains("\"{{SOURCE_ROOT}}/README.md\""));
        assert!(rendered.contains("\"{{THREE_SHOT_ROOT}}/v12-checklist.md\""));
    }

    #[test]
    fn bounty_config_contains_bounty_criteria_and_no_v12_checklist() {
        let temp = tempfile::tempdir().unwrap();
        let project = temp.path();
        let source_root = project.join("audit-workspace/bounty-protocol");
        fs::create_dir_all(&source_root).unwrap();
        fs::write(source_root.join("README.md"), "# Bounty").unwrap();

        let mut repo = repo_paths(project.join("audit-workspace"), Vec::new(), None);
        repo.repo_name = "bounty-protocol".to_string();
        repo.audit_type = AuditType::Code4renaBounty;
        let report = project.join("bounty-protocol/report/audit-report.md");
        let rendered = render_config(
            "bounty-protocol",
            &source_root,
            &project.join("bounty-protocol"),
            &report,
            &context_docs(&repo, &source_root).unwrap(),
            &repo.audit_type,
        );

        assert!(rendered.contains("validation_profile: \"code4rena-bounty\""));
        assert!(rendered.contains("\"{{THREE_SHOT_ROOT}}/code4rena-bounty-criteria.md\""));
        assert!(!rendered.contains("v12-checklist.md"));
    }

    #[test]
    fn immunefi_config_contains_generated_bounty_artifacts() {
        let temp = tempfile::tempdir().unwrap();
        let project = temp.path();
        let source_root = project.join("audit-workspace/ssv-network");
        fs::create_dir_all(&source_root).unwrap();
        fs::write(source_root.join("README.md"), "# SSV").unwrap();

        let artifact_dir = project.join("audit-docs/ssv-network");
        fs::create_dir_all(&artifact_dir).unwrap();
        let docs = artifact_dir.join("ssv-network-docs.md");
        let scope = artifact_dir.join("ssv-network-scope.md");
        let scope_txt = artifact_dir.join("ssv-network-scope.txt");
        let rules = artifact_dir.join("ssv-network-immunefi-bounty-rules.md");
        let rubric = artifact_dir.join("ssv-network-immunefi-severity-rubric.md");
        let poc_runtime = artifact_dir.join("ssv-network-immunefi-poc-runtime.md");
        for path in [&docs, &scope, &scope_txt, &rules, &rubric, &poc_runtime] {
            fs::write(path, "# generated").unwrap();
        }

        let mut repo = repo_paths(
            project.join("audit-workspace"),
            vec![docs, rules, rubric, poc_runtime],
            Some(scope),
        );
        repo.repo_name = "ssv-network".to_string();
        repo.scoped_files = Some(scope_txt);
        repo.audit_type = AuditType::ImmunefiBugBounty;
        let report = project.join("ssv-network/report/audit-report.md");
        let rendered = render_config(
            "ssv-network",
            &source_root,
            &project.join("ssv-network"),
            &report,
            &context_docs(&repo, &source_root).unwrap(),
            &repo.audit_type,
        );

        assert!(rendered.contains("validation_profile: \"immunefi-bounty\""));
        assert!(rendered.contains("audit-docs/ssv-network/ssv-network-scope.md"));
        assert!(rendered.contains("audit-docs/ssv-network/ssv-network-scope.txt"));
        assert!(rendered.contains("audit-docs/ssv-network/ssv-network-immunefi-bounty-rules.md"));
        assert!(
            rendered.contains("audit-docs/ssv-network/ssv-network-immunefi-severity-rubric.md")
        );
        assert!(rendered.contains("audit-docs/ssv-network/ssv-network-immunefi-poc-runtime.md"));
        assert!(!rendered.contains("code4rena-bounty-criteria.md"));
        assert!(!rendered.contains("v12-checklist.md"));
    }

    #[test]
    fn config_slug_preserves_repo_folder_identity() {
        assert_eq!(config_slug("2026-01-olas"), "2026-01-olas");
        assert_eq!(
            config_slug("2026-01-olas/contracts"),
            "2026-01-olas-contracts"
        );
    }
}
